repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=100]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]

  # Flake8 disabled temporarily due to extensive style cleanup needed
  # - repo: https://github.com/pycqa/flake8
  #   rev: 6.0.0
  #   hooks:
  #     - id: flake8
  #       args: [--max-line-length=100, --ignore=E203,W503,E501,F541,E221,E231,E402,F401,F841,F811]

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: ./venv/bin/python -m pytest
        language: system
        args: [tests/unit/shared/, tests/unit/agent/, --tb=short, -x, -v]
        files: \.py$
        stages: [pre-commit]
        pass_filenames: false
        always_run: true

      - id: coverage-check
        name: coverage-check
        entry: ./venv/bin/python -m pytest
        language: system
        args: [tests/unit/shared/, tests/unit/agent/, --cov=shared.models, --cov=agent.core.agent, --cov-fail-under=80, --tb=short]
        files: \.py$
        stages: [pre-push]
        pass_filenames: false
        always_run: true
